# Generated by Django 3.1.7 on 2021-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_orders',
            name='status',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
